## Quick overview
Here are some quick examples of what you can do with `xarray.DataArray` objects. Everything is explained in much more detail in the rest of the documentation.

In [5]:
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
# create a DataArray
data = np.random.rand(2, 3)
da = xr.DataArray(data)
da

<xarray.DataArray (dim_0: 2, dim_1: 3)>
array([[0.51219 , 0.791741, 0.917879],
       [0.548983, 0.870207, 0.369761]])
Dimensions without coordinates: dim_0, dim_1

In [3]:
# add coordinates and dimensions
coords = {'x': ['a', 'b']}
dims = ('x', 'y')
da = xr.DataArray(data, coords=coords, dims=dims)
da

<xarray.DataArray (x: 2, y: 3)>
array([[0.51219 , 0.791741, 0.917879],
       [0.548983, 0.870207, 0.369761]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [27]:
# access the different DataArray properties
print('Values:', da.values)
print('Dimensions:', da.dims)
print(da.coords)
print('Attributes:', da.attrs)

Values: [[0.42000529 0.75682862 0.04448223]
 [0.41255157 0.92480711 0.61577582]]
Dimensions: ('x', 'y')
Coordinates:
  * x        (x) <U1 'a' 'b'
Attributes: OrderedDict()


In [28]:
# metadata is copied directly from a pandas.Series or pandas.DataFrame
data = np.random.rand(3)
series = pd.Series(data, index=list('abc'), name='foo')
xr.DataArray(series)

<xarray.DataArray 'foo' (dim_0: 3)>
array([0.319231, 0.156316, 0.449283])
Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

## Indexing
`xarray` supports four kinds of indexing. These operations are just as fast as in `pandas`, because they borrow `pandas`' indexing machinery.

In [47]:
# positional indexing by integer label (like numpy)
da[0]

<xarray.DataArray (y: 3)>
array([0.420005, 0.756829, 0.044482])
Coordinates:
    x        <U1 'a'
Dimensions without coordinates: y

In [48]:
# positional indexing by coordinate label (like pandas)
da.loc['b']

<xarray.DataArray (y: 3)>
array([0.412552, 0.924807, 0.615776])
Coordinates:
    x        <U1 'b'
Dimensions without coordinates: y

In [57]:
# by dimension name and integer label
da.isel(x=[1])

<xarray.DataArray (x: 1, y: 3)>
array([[0.412552, 0.924807, 0.615776]])
Coordinates:
  * x        (x) <U1 'b'
Dimensions without coordinates: y

In [58]:
# by dimension name and coordinate label
da.sel(x=['a'])

<xarray.DataArray (x: 1, y: 3)>
array([[0.420005, 0.756829, 0.044482]])
Coordinates:
  * x        (x) <U1 'a'
Dimensions without coordinates: y

## Computation
`DataArray`s work very similarly to `numpy.ndarray`s.

In [63]:
# arithmetic operations
da * 2 + 10

<xarray.DataArray (x: 2, y: 3)>
array([[10.840011, 11.513657, 10.088964],
       [10.825103, 11.849614, 11.231552]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [64]:
# applying functions
np.sin(da)

<xarray.DataArray (x: 2, y: 3)>
array([[0.407765, 0.686619, 0.044468],
       [0.400948, 0.798505, 0.577592]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [65]:
# matrix operations
da.T

<xarray.DataArray (y: 3, x: 2)>
array([[0.420005, 0.412552],
       [0.756829, 0.924807],
       [0.044482, 0.615776]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [67]:
# aggregation operations can use dimensions instead of axis numbers
da.sum(dim='y')

<xarray.DataArray (x: 2)>
array([1.221316, 1.953135])
Coordinates:
  * x        (x) <U1 'a' 'b'

In [102]:
# arithmetic operations broadcast based on dimension name
a = xr.DataArray([1,2,3], dims='base')
b = xr.DataArray(10**np.arange(4), dims='magnitude')
print(a, '\n\n', b)

<xarray.DataArray (base: 3)>
array([1, 2, 3])
Dimensions without coordinates: base 

 <xarray.DataArray (magnitude: 4)>
array([   1,   10,  100, 1000])
Dimensions without coordinates: magnitude


In [105]:
da = a*b
da.assign_coords(base=a.values, magnitude=b.values)

<xarray.DataArray (base: 3, magnitude: 4)>
array([[   1,   10,  100, 1000],
       [   2,   20,  200, 2000],
       [   3,   30,  300, 3000]])
Coordinates:
  * base       (base) int64 1 2 3
  * magnitude  (magnitude) int64 1 10 100 1000

In [9]:
xr.tutorial.

<module 'xarray.tutorial' from '/Users/oberrauch/miniconda3/envs/oggm_env/lib/python3.6/site-packages/xarray/tutorial.py'>

In [11]:
ds = xr.tutorial.load_dataset('air_temperature')

In [14]:
ds

<xarray.Dataset>
Dimensions:  (lat: 25, lon: 53, time: 2920)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 62.5 60.0 57.5 55.0 52.5 ...
  * lon      (lon) float32 200.0 202.5 205.0 207.5 210.0 212.5 215.0 217.5 ...
  * time     (time) datetime64[ns] 2013-01-01 2013-01-01T06:00:00 ...
Data variables:
    air      (time, lat, lon) float32 241.2 242.5 243.5 244.0 244.09999 ...
Attributes:
    Conventions:  COARDS
    title:        4x daily NMC reanalysis (1948)
    description:  Data is from NMC initialized reanalysis\n(4x/day).  These a...
    platform:     Model
    references:   http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanaly...